version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    networks:
        - servise-flask
#    ports:
#        - "5432:5432"
  web:
    build: .
    command: python app.py 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
    networks:
        - servise-flask

  redis:
    image: redis

    networks:
      - servise-flask

  celery:
    build: .
    command: "celery -A task.celery worker -B --loglevel=info
"
    volumes:
      - .:/code
    depends_on:
      - db
      - web
      - redis

    networks:
        - servise-flask


networks:
  servise-flask:
    name: servise-flask
    driver: bridge
    external: true
